on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.x]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - env:
          CLTK_GIT_VSN: 1.0.0b6
        run: |
          python -m venv .
          source ./bin/activate
          python -m pip install --upgrade pip
          pip install git+https://github.com/cltk/cltk.git@${CLTK_GIT_VSN:?}#egg=cltk
          pip install pyyaml
          curl -fsSLO https://raw.githubusercontent.com/cltk/cltk/${CLTK_GIT_VSN:?}/scripts/download_all_models.py | python
      - run: |
          source ./bin/activate
          python -m doctest -fv $(find . -type f -name '*.rst')
